name: Nuget Pack n Push

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2.1 #populates GIT_TAG_NAME
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: nuget pack IntelliTect.Coalesce.Vue.Template.nuspec -Version ${GIT_TAG_NAME}
    - name: Push
      run: dotnet nuget push **\*.nupkg -k ${NUGET_KEY}
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
